### ISSUE TITLE
elasticsearch-analysis-jieba安装出错

### ISSUE THREAD

**Issue by henghenghahai** [k5h9999/elasticsearch-analysis-jieba#1]
Hi K5h9999,
   我修改了pom.xml中的三处5.5.3成5.6.4后（我的es是5.6.4）,然后重新打包成zip文件，但在安装时出错，如下，这个是什么问题呢，谢谢。
[root@server01 ~]# /usr/share/elasticsearch/bin/elasticsearch-plugin install file:///root/elasticsearch-analysis-jieba-master.zip 
-> Downloading file:///root/elasticsearch-analysis-jieba-master.zip
[=================================================] 100%?? 
ERROR: `elasticsearch` directory is missing in the plugin zip

**Comment by k5h9999** [comment]
你好，install的时候会生成一个elasticsearch-analysis-jieba-5.6.4.zip这个文件，安装的时候是把解压的zip文件解压到plugin文件夹里的命名一个jieba的文件夹里，启动即可
