### ISSUE TITLE
请问这个支持词库扩展和热更新吗？

### ISSUE THREAD

**Issue by yanshuang16** [k5h9999/elasticsearch-analysis-jieba#3]

**Comment by k5h9999** [comment]
可以做到热更新，参考：https://blog.csdn.net/moxiong3212/article/details/79340594

**Comment by yanshuang16** [comment]
感谢您的回复，ik分词器有ik_smart和ik_max_word, 我测了一些例子，发现这版的结巴和ik_smart分析的效果一样，请问这版结巴能做到 ik_max_word那样更细的分词么？要怎么做呢？

**Comment by k5h9999** [comment]
建议你用ik分词，ik分词比较轻量级，有粗粒度和细粒度之分，我们也都是用ik分词处理；
具体你也可以参考结巴的细粒度分词url：https://blog.csdn.net/guotong1988/article/details/80690523

**Comment by yanshuang16** [comment]
好的，谢谢 @k5h9999
